name: Sync from ZIP upload (incoming/)

on:
  push:
    paths:
      - 'incoming/*.zip'

jobs:
  unzip-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract ZIP
        run: |
          mkdir extracted
          unzip -o incoming/*.zip -d extracted

      - name: Copy extracted to repo
        run: |
          rsync -av extracted/ ./
          rm -rf incoming/*.zip

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Sync from ZIP upload"
          git push
