name: Sync from ZIP upload (incoming/)

on:
  push:
    paths:
      - 'incoming/*.zip'

concurrency:
  group: sync-incoming
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  unzip-and-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # Garante que começamos exatamente do último remoto
      - name: Align working tree to origin/main
        shell: bash
        run: |
          set -euxo pipefail
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          BR="${GITHUB_REF_NAME:-main}"
          git fetch origin "$BR"
          git checkout "$BR"
          git reset --hard "origin/$BR"

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y unzip rsync

      - name: Find latest ZIP in incoming/
        id: findzip
        shell: bash
        run: |
          set -euxo pipefail
          LATEST="$(ls -t incoming/*.zip 2>/dev/null | head -n1 || true)"
          if [ -z "$LATEST" ]; then
            echo "Nenhum ZIP em incoming/"; exit 1
          fi
          echo "zip_path=$LATEST" >> "$GITHUB_OUTPUT"
          echo "ZIP encontrado: $LATEST"

      - name: Validate ZIP paths (no / or ../)
        shell: bash
        run: |
          set -euxo pipefail
          LIST="$(zipinfo -1 "${{ steps.findzip.outputs.zip_path }}")"
          if echo "$LIST" | grep -E '(^/|(^|/)\.\.(/|$))' >/dev/null; then
            echo "ZIP contém caminhos inválidos (absolutos ou ../). Abortando."; exit 2
          fi

      - name: Unzip payload
        shell: bash
        run: |
          set -euxo pipefail
          rm -rf /tmp/_unz && mkdir -p /tmp/_unz
          unzip -q "${{ steps.findzip.outputs.zip_path }}" -d /tmp/_unz
          # Bloqueia symlinks no pacote
          if find /tmp/_unz -xtype l -print -quit | grep .; then
            echo "ZIP contém symlinks. Abortando por segurança."; exit 3
          fi
          echo "Conteúdo extraído:"; ls -la /tmp/_unz
          ROOT="/tmp/_unz"
          DIRS=$(find /tmp/_unz -mindepth 1 -maxdepth 1 -type d | wc -l)
          FILES=$(find /tmp/_unz -mindepth 1 -maxdepth 1 -type f | wc -l)
          if [ "$DIRS" -eq 1 ] && [ "$FILES" -eq 0 ]; then
            ROOT="$(find /tmp/_unz -mindepth 1 -maxdepth 1 -type d | head -n1)"
          fi
          echo "ROOT=$ROOT" | tee /tmp/root_path

      - name: Sync files to repo (com proteção)
        shell: bash
        run: |
          set -euxo pipefail
          ROOT="$(cat /tmp/root_path)"
          # 1) Sincroniza tudo, com links seguros e filtros que PROTEGEM .github/ e incoming/
          rsync -av --delete --safe-links \
            --exclude '.git' \
            --exclude 'node_modules' \
            --exclude 'dist' \
            --filter='P .github/***' \
            --filter='P incoming/***' \
            "$ROOT"/ ./
          # 2) RESTAURA QUALQUER deleção acidental das pastas protegidas
          git checkout -- .github .github/workflows incoming || true
          # 3) Mostra o que ficou staged/modified
          git status --porcelain

      - name: Remove processed ZIP
        shell: bash
        run: |
          set -euxo pipefail
          rm -f "${{ steps.findzip.outputs.zip_path }}" || true

      - name: Commit & push (com rebase e retry)
        shell: bash
        run: |
          set -euxo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          BR="${GITHUB_REF_NAME:-main}"
          # alinhar índice/HEAD ao remoto antes de criar commit => tende a fast‑forward
          git fetch origin "$BR"
          git checkout "$BR"
          git reset --soft "origin/$BR"

          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore: sync from incoming ZIP $(date +'%Y-%m-%d %H:%M %Z')"

            # 1ª tentativa; se rejeitar, entra no fluxo de retry sem derrubar o job
            if ! git push; then
              echo "Push rejeitado (non-fast-forward). Rebase e tentar novamente..."
              n=1
              while [ $n -le 3 ]; do
                git fetch origin "$BR"
                # tenta rebase direto; em caso de conflito, aborta e usa pull --rebase
                if ! git rebase "origin/$BR"; then
                  git rebase --abort || true
                  git pull --rebase origin "$BR" || true
                fi
                if git push; then
                  echo "Push OK após retry #$n"
                  break
                fi
                n=$((n+1))
                sleep 1
              done
              # tentativa final (falha explicitamente se ainda estiver rejeitando)
              git push
            fi
          else
            echo "Sem mudanças para commit."
          fi
