name: Sync from ZIP upload (incoming/)

on:
  push:
    paths:
      - 'incoming/*.zip'
  workflow_dispatch: {}  # rodar manualmente a versão nova

concurrency:
  group: sync-incoming
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  unzip-and-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Version marker
        run: echo "SYNC WF v6 - PR mode + ROOT sanitize"

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Align working tree to origin/main
        shell: bash
        run: |
          set -euxo pipefail
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          BR="${GITHUB_REF_NAME:-main}"
          git fetch origin "$BR"
          git checkout "$BR"
          git reset --hard "origin/$BR"

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y unzip rsync zipinfo

      - name: Find latest ZIP in incoming/
        id: findzip
        shell: bash
        run: |
          set -euxo pipefail
          LATEST="$(ls -t incoming/*.zip 2>/dev/null | head -n1 || true)"
          if [ -z "$LATEST" ]; then
            echo "Nenhum ZIP em incoming/"; exit 1
          fi
          echo "zip_path=$LATEST" >> "$GITHUB_OUTPUT"
          echo "ZIP encontrado: $LATEST"

      - name: Validate ZIP paths (no / or ../)
        shell: bash
        run: |
          set -euxo pipefail
          LIST="$(zipinfo -1 "${{ steps.findzip.outputs.zip_path }}")"
          if echo "$LIST" | grep -E '(^/|(^|/)\.\.(/|$))' >/dev/null; then
            echo "ZIP contém caminhos inválidos (absolutos ou ../). Abortando."; exit 2
          fi

      - name: Unzip payload
        shell: bash
        run: |
          set -euxo pipefail
          rm -rf /tmp/_unz && mkdir -p /tmp/_unz
          unzip -q "${{ steps.findzip.outputs.zip_path }}" -d /tmp/_unz
          # Bloqueia symlinks no pacote
          if find /tmp/_unz -xtype l -print -quit | grep .; then
            echo "ZIP contém symlinks. Abortando por segurança."; exit 3
          fi
          echo "Conteúdo extraído:"; ls -la /tmp/_unz
          ROOT="/tmp/_unz"
          DIRS=$(find /tmp/_unz -mindepth 1 -maxdepth 1 -type d | wc -l)
          FILES=$(find /tmp/_unz -mindepth 1 -maxdepth 1 -type f | wc -l)
          if [ "$DIRS" -eq 1 ] && [ "$FILES" -eq 0 ]; then
            ROOT="$(find /tmp/_unz -mindepth 1 -maxdepth 1 -type d | head -n1)"
          fi
          echo "ROOT: $ROOT"
          printf '%s' "$ROOT" > /tmp/root_path   # grava SOMENTE o caminho

      - name: Sync files to repo (com proteção)
        shell: bash
        run: |
          set -euxo pipefail
          RAW="$(cat /tmp/root_path || true)"
          # higieniza mesmo que algum run antigo tenha escrito "ROOT=/tmp/_unz"
          ROOT="${RAW#ROOT=}"
          ROOT="${ROOT%/}"
          echo "ROOT sanitizado: $ROOT"
          test -n "$ROOT" && test -d "$ROOT"

          # Não tocar em .github/ nem incoming/ durante a sync
          rsync -av --delete --safe-links \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'incoming' \
            --exclude 'node_modules' \
            --exclude 'dist' \
            "$ROOT"/ ./

          # Cinto extra: restaura caso algo toque nessas pastas
          git checkout -- .github .github/workflows incoming || true
          git status --porcelain

      - name: Remove processed ZIP
        shell: bash
        run: |
          set -euxo pipefail
          rm -f "${{ steps.findzip.outputs.zip_path }}" || true

      - name: Prepare PR branch
        id: br
        shell: bash
        run: |
          set -euxo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          BASE="origin/${GITHUB_REF_NAME:-main}"
          TS="$(date +'%Y%m%d-%H%M%S')"
          BRANCH="bot/sync-incoming-${TS}"

          git fetch origin
          git checkout -B "${BRANCH}" "${BASE}"

          if [ -n "$(git status --porce]()
