name: (DISABLED) Sync from ZIP upload (incoming/)

on:
  workflow_dispatch: {}  # não dispara mais por push; só manual e faz nada

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Legacy workflow disabled. Use 'Manual Sync from incoming ZIP (v8)'."
